### ISSUE TITLE
Russian translation tracking

### ISSUE THREAD

**Issue by MasedMSD** [grammyjs/website#1088]
This issue is for tracking the translation progress of all pages. It will be closed when the translation of the whole documentation is finished.

Some of the terms cannot be translated correctly or they're gonna sound weird:
- Middleware
- Plugin names *Some of them won't sound weird, but I decided to leave them in the original name so users can have associations
- Long Polling
- Error codes and the message they send in [faq.md](../tree/main/site/docs/resources/faq.md) *I didn't translate this to make it easier for users to find a solution in original.
- Deep Linking

These words can be replenished depending on the work done

### Before translating
* Before you start, read the [translation guide](https://github.com/grammyjs/website/blob/main/TRANSLATING.md)
* Pick one untranslated page from the list below and start translating it locally

### While translating
* **DO NOT** just copy the translation from some translator tool, use your own native-speaker skills

### After translating
* Create PR from your fork against the [`ru`](https://github.com/grammyjs/website/tree/ru) branch

### Landing Page and Config
* [x]  [404.md](../tree/main/site/docs/404.md)
* [x]  [README.md](../tree/main/site/docs/README.md)
* [x]  [config.ts](https://github.com/grammyjs/website/blob/main/site/docs/.vitepress/config.ts)
* [x]  [locale](https://github.com/grammyjs/website/blob/main/site/docs/.vitepress/configs/locales/en.ts)

#### Guide
* [x]  [README.md](../tree/main/site/docs/guide/README.md)
* [x]  [introduction.md](../tree/main/site/docs/guide/introduction.md)
* [x]  [getting-started.md](../tree/main/site/docs/guide/getting-started.md)
* [x]  [basics.md](../tree/main/site/docs/guide/basics.md)
* [x]  [context.md](../tree/main/site/docs/guide/context.md)
* [x]  [api.md](../tree/main/site/docs/guide/api.md)
* [x]  [filter-queries.md](../tree/main/site/docs/guide/filter-queries.md)
* [x]  [commands.md](../tree/main/site/docs/guide/commands.md)
* [x]  [reactions.md](../tree/main/site/docs/guide/reactions.md)
* [x]  [middleware.md](../tree/main/site/docs/guide/middleware.md)
* [x]  [errors.md](../tree/main/site/docs/guide/errors.md)
* [x]  [files.md](../tree/main/site/docs/guide/files.md)
* [x]  [games.md](../tree/main/site/docs/guide/games.md)
* [x]  [deployment-types.md](../tree/main/site/docs/guide/deployment-types.md)

#### Advanced
* [x]  [README.md](../tree/main/site/docs/advanced/README.md)
* [x]  [middleware.md](../tree/main/site/docs/advanced/middleware.md)
* [x]  [structuring.md](../tree/main/site/docs/advanced/structuring.md)
* [x]  [scaling.md](../tree/main/site/docs/advanced/scaling.md)
* [x]  [reliability.md](../tree/main/site/docs/advanced/reliability.md)
* [x]  [flood.md](../tree/main/site/docs/advanced/flood.md)
* [x]  [transformers.md](../tree/main/site/docs/advanced/transformers.md)
* [x]  [business.md](../tree/main/site/docs/advanced/business.md)
* [x]  [proxy.md](../tree/main/site/docs/advanced/proxy.md)
* [x]  [deployment.md](../tree/main/site/docs/advanced/deployment.md)

#### Introduction
* [x]  [README.md](../tree/main/site/docs/plugins/README.md)
* [x]  [guide.md](../tree/main/site/docs/plugins/guide.md)

#### Built-in
* [x]  [session.md](../tree/main/site/docs/plugins/session.md)
* [x]  [keyboard.md](../tree/main/site/docs/plugins/keyboard.md)
* [x]  [inline-query.md](../tree/main/site/docs/plugins/inline-query.md)
* [x]  [media-group.md](../tree/main/site/docs/plugins/media-group.md)

#### Official
* [x]  [conversations.md](../tree/main/site/docs/plugins/conversations.md)
* [x]  [menu.md](../tree/main/site/docs/plugins/menu.md)
* [x]  [stateless-question.md](../tree/main/site/docs/plugins/stateless-question.md)
* [x]  [runner.md](../tree/main/site/docs/plugins/runner.md)
* [x]  [hydrate.md](../tree/main/site/docs/plugins/hydrate.md)
* [x]  [auto-retry.md](../tree/main/site/docs/plugins/auto-retry.md)
* [x]  [transformer-throttler.md](../tree/main/site/docs/plugins/transformer-throttler.md)
* [x]  [ratelimiter.md](../tree/main/site/docs/plugins/ratelimiter.md)
* [x]  [files.md](../tree/main/site/docs/plugins/files.md)
* [x]  [i18n.md](../tree/main/site/docs/plugins/i18n.md)
* [x]  [fluent.md](../tree/main/site/docs/plugins/fluent.md)
* [x]  [router.md](../tree/main/site/docs/plugins/router.md)
* [x]  [emoji.md](../tree/main/site/docs/plugins/emoji.md)
* [x]  [parse-mode.md](../tree/main/site/docs/plugins/parse-mode.md)
* [x]  [chat-members.md](../tree/main/site/docs/plugins/chat-members.md)
* [x]  [commands.md](../tree/main/site/docs/plugins/commands.md)

#### Third-party
* [x]  [console-time.md](../tree/main/site/docs/plugins/console-time.md)
* [x]  [middlewares.md](../tree/main/site/docs/plugins/middlewares.md)
* [x]  [autoquote.md](../tree/main/site/docs/plugins/autoquote.md)

#### grammY
* [x]  [about.md](../tree/main/site/docs/resources/about.md)
* [x]  [faq.md](../tree/main/site/docs/resources/faq.md)
* [x]  [comparison.md](../tree/main/site/docs/resources/comparison.md)

#### Overview
* [x]  [comparison.md](../tree/main/site/docs/hosting/comparison.md)

#### Tutorials
* [x]  [vps.md](../tree/main/site/docs/hosting/vps.md)
* [x]  [deno-deploy.md](../tree/main/site/docs/hosting/deno-deploy.md)
* [x]  [supabase.md](../tree/main/site/docs/hosting/supabase.md)
* [x]  [cloudflare-workers.md](../tree/main/site/docs/hosting/cloudflare-workers.md)
* [x]  [cloudflare-workers-nodejs.md](../tree/main/site/docs/hosting/cloudflare-workers-nodejs.md)
* [x]  [fly.md](../tree/main/site/docs/hosting/fly.md)
* [x]  [firebase.md](../tree/main/site/docs/hosting/firebase.md)
* [x]  [vercel.md](../tree/main/site/docs/hosting/vercel.md)
* [x]  [zeabur-deno.md](../tree/main/site/docs/hosting/zeabur-deno.md)
* [x]  [zeabur-nodejs.md](../tree/main/site/docs/hosting/zeabur-nodejs.md)
* [x]  [heroku.md](../tree/main/site/docs/hosting/heroku.md)
