### ISSUE TITLE
Uzbek translation tracking

### ISSUE THREAD

**Issue by mcpeblocker** [grammyjs/website#215]
This issue is tracking for translating Uzbek documentation.

For someone who wants to join to translate documentation to the Uzbek language, you can take a look at this issue, find out the untranslated section.

This issue will be closed when the documentation is largely translated.

There is more detail about translation in [TRANSLATING](https://github.com/grammyjs/website/blob/main/TRANSLATING.md) guide, please read it first!

Here are some of the formats we are following:

**First and the most important:**
**DO NOT** just copy the section to google translator or something like that and paste back the result

Second, some words we are not going to translate:

*   bot
*   update
*   keyboard / inline keyboard
*   webhook/polling
*   payload
*   middleware
*   ...(feel free to add more, but make sense)

- - -

Bu issue dokumentatsiyani O'zbek tiliga tarjima qilinishini kuzatib borish uchun.

Dokumentatsiyani O'zbek tiliga tarjima qilishga o'z hissangizni qo'shmoqchi bo'lsangiz bu issueni ko'rib chiqib, tarjima qilinmagan bo'limni topishingiz mumkin..

Bu issue dokumentatsiya to'liq tarjima qilinganda yopiladi.

Tarjima qilish haqida [TRANSLATING](https://github.com/grammyjs/website/blob/main/TRANSLATING.md) qo'llanmasida ko'proq ma'lumot bor, oldin shuni o'qishni maslahat beramiz.

Quyida biz amal qilayotgan ba'zi bir formatlar keltirilgan:

**Birinchi va eng muhimi:**
Matnni shunchaki google tarjimon yoki shunga o'xshash platformaga **TARJIMA QILDIRMANG**

Ikkinchi, ba'zi bir so'zlarni tarjima qilish kerak emas:

*   bot
*   update
*   keyboard / inline keyboard
*   webhook/polling
*   payload
*   middleware
*   ...(boshqa so'zlarni bemalol qo'shishingiz mumkin)

---

## Readme

- [x] README.md -> [Pull Request](https://github.com/grammyjs/website/pull/218)

## Advanced

- [ ] deployment.md
- [ ] flood.md
- [x] middleware.md -> [Pull Request](https://github.com/grammyjs/website/pull/226)
- [ ] proxy.md
- [x] README.md -> [Pull Request](https://github.com/grammyjs/website/pull/221)
- [ ] reliability.md
- [ ] scaling.md
- [x] structuring.md -> [Pull Request](https://github.com/grammyjs/website/pull/225)
- [ ] transformers.md

## Demo

- [ ] examples.md
- [ ] README.md

## Guide

- [ ] api.md
- [ ] basics.md
- [ ] commands.md
- [ ] context.md
- [ ] deployment-types.md
- [ ] errors.md
- [ ] files.md
- [ ] filter-queries.md
- [ ] games.md
- [ ] getting-started.md
- [ ] inline-queries.md
- [ ] introduction.md
- [ ] middleware.md
- [x] README.md -> [Pull request](https://github.com/grammyjs/website/pull/227)

## Hosting

- [ ] deno-deploy.md
- [ ] gcf.md
- [ ] heroku.md

## Plugins

- [ ] auto-retry.md
- [ ] command-filter.md
- [ ] console-time.md
- [ ] files.md
- [ ] hydratate.md
- [ ] i18n.md
- [ ] keyboard.md
- [ ] menu.md
- [ ] parse-mode.md
- [ ] ratelimiter.md
- [ ] README.md
- [ ] router.md
- [ ] runner.md
- [ ] session.md
- [ ] stateless-question.md
- [ ] transformer-throttler.md

## Resources

- [ ] comparison.md
- [ ] faq.md

**Comment by KnorpelSenf** [comment]
Is this list up to date? I see four linked pull requests, but [five](https://github.com/grammyjs/website/pulls?q=is%3Apr+sort%3Aupdated-desc+label%3A%22%F0%9F%87%BA%F0%9F%87%BF+UZ%22) exist. Am I missing something? 🤔

**Comment by KnorpelSenf** [comment]
Oh could it be that you only link things here that are already merged? There is no need for this. The idea is to link the open pull requests here so people can see which articles are in progress. Then they can join in without having to go through the complete list of pull requests first. Having links to already merged pull requests is not necessary.

**Comment by mcpeblocker** [comment]
> Oh could it be that you only link things here that are already merged? There is no need for this. The idea is to link the open pull requests here so people can see which articles are in progress. Then they can join in without having to go through the complete list of pull requests first. Having links to already merged pull requests is not necessary.

Sorry for that. Thank you for info )

**Comment by KnorpelSenf** [comment]
Are you still invested in this?

It's completely fine if you decide to prioritise other projects. In that case, I'd close this.

**Comment by mcpeblocker** [comment]
As you mentioned, we are busy with other things. Therefore, it would be appropriate to close it for now.
