### ISSUE TITLE
Indonesian Translation Tracking

### ISSUE THREAD

**Issue by CikiMomogi** [grammyjs/website#369]
# 🇮🇩 Indonesian
## Deskripsi
Issue ini digunakan untuk memantau proses translasi semua halaman. Issue akan ditutup ketika semua dokumentasi berhasil diselesaikan.

### Menjadi Penerjemah
1. Sebelum memulai, **pahami** dulu [panduan berkontribusi untuk penerjemah](https://github.com/grammyjs/website/blob/main/CONTRIBUTING.md#translations).
2. Terjemahkan dengan bahasa yang kamu kuasai. **JANGAN** hanya copas alias copy-paste mentah-mentah dari google translate. Gunakan pemahaman kamu agar menghasilkan terjemahan yang baik dan enak dibaca.
3. Ambil satu halaman yang belum diterjemahkan. Terus terjemahkan. Kalau sudah, buat pull request (PR) sesuai panduan di point satu di atas. Ingat, **satu PR untuk satu halaman** agar mudah dikerjakan dan dikoreksi.

### Menjadi Penyunting
Silahkan dikoreksi PR translasi yang sudah dibuat. Tambahkan catatan jika diperlukan.

## Catatan
Kata-kata yang berhubungan dengan _methods_, nama _function_, _variables_... **tidak perlu** diterjemahkan. Berikut beberapa contohnya:
```
bot
update
keyboard / inline keyboard
webhook
payload
... (dan lain-lain)
```

# 🇬🇧 English
## Description
This issue is for tracking the translation progress of all pages and will be closed when the documentation is finished.

### Being a translator
1. Read [how to contribute in translations](https://github.com/grammyjs/website/blob/main/CONTRIBUTING.md#translations)
2. Translate with your native-speaker level, **DO NOT** just copy the section to some translator tool and paste back the result
3. Take one untranslated page, translate and create PR from your fork to the main project. One PR for page, to better split in parallel the work and less tired reviews

### Being a reviewer
Find the PR's created for translations and review them. Add all notes that you consider.

## Note
Words related to _methods_, _function_ names, _variables_... **mustn't** be translated. Here are some examples:

```
bot
update
keyboard / inline keyboard
webhook
payload
... (feel free to add more, but make sense)
```
# 📝 Translation progress
## README
- [x] [README.md](https://github.com/grammyjs/website/blob/main/site/docs/README.md) => [PR#1](https://github.com/CikiMomogi/website/pull/7), [PR#2](https://github.com/CikiMomogi-grammY/website/pull/66)

## Advanced
- [x] [deployment.md](https://github.com/grammyjs/website/blob/main/site/docs/advanced/deployment.md) => [PR](https://github.com/CikiMomogi/website/pull/9)
- [x] [flood.md](https://github.com/grammyjs/website/blob/main/site/docs/advanced/flood.md) => [PR](https://github.com/CikiMomogi/website/pull/28)
- [x] [middleware.md](https://github.com/grammyjs/website/blob/main/site/docs/advanced/middleware.md) => [PR](https://github.com/CikiMomogi/website/pull/24)
- [x] [proxy.md](https://github.com/grammyjs/website/blob/main/site/docs/advanced/proxy.md) => [PR](https://github.com/CikiMomogi/website/pull/30)
- [x] [README.md](https://github.com/grammyjs/website/blob/main/site/docs/advanced/README.md) => [PR](https://github.com/CikiMomogi/website/pull/8)
- [x] [reliability.md](https://github.com/grammyjs/website/blob/main/site/docs/advanced/reliability.md) => [PR](https://github.com/CikiMomogi/website/pull/27)
- [x] [scaling.md](https://github.com/grammyjs/website/blob/main/site/docs/advanced/scaling.md) => [PR](https://github.com/CikiMomogi/website/pull/26)
- [x] [structuring.md](https://github.com/grammyjs/website/blob/main/site/docs/advanced/structuring.md) => [PR](https://github.com/CikiMomogi/website/pull/25)
- [x] [transformers.md](https://github.com/grammyjs/website/blob/main/site/docs/advanced/transformers.md) => [PR](https://github.com/CikiMomogi/website/pull/29)

## Demo
- [x] [examples.md](https://github.com/grammyjs/website/blob/main/site/docs/demo/examples.md) => [PR](https://github.com/CikiMomogi/website/pull/53)
- [x] [README.md](https://github.com/grammyjs/website/blob/main/site/docs/demo/README.md) => [PR](https://github.com/CikiMomogi/website/pull/54)

## Guide
- [x] [api.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/api.md) => [PR](https://github.com/CikiMomogi/website/pull/15)
- [x] [basics.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/basics.md) => [PR](https://github.com/CikiMomogi/website/pull/13)
- [x] [commands.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/commands.md) => [PR](https://github.com/CikiMomogi/website/pull/17)
- [x] [context.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/context.md) => [PR](https://github.com/CikiMomogi/website/pull/14)
- [x] [deployment-types.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/deployment-types.md) => [PR](https://github.com/CikiMomogi/website/pull/23)
- [x] [errors.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/errors.md) => [PR](https://github.com/CikiMomogi/website/pull/19)
- [x] [files.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/files.md) => [PR](https://github.com/CikiMomogi/website/pull/21)
- [x] [filter-queries.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/filter-queries.md) => [PR](https://github.com/CikiMomogi/website/pull/16)
- [x] [games.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/games.md) => [PR](https://github.com/CikiMomogi/website/pull/22)
- [x] [getting-started.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/getting-started.md) => [PR#1](https://github.com/CikiMomogi/website/pull/12), [PR#2](https://github.com/CikiMomogi-grammY/website/pull/68)
- [x] [inline-queries.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/inline-queries.md) => [PR](https://github.com/CikiMomogi/website/pull/20)
- [x] [introduction.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/introduction.md) => [PR](https://github.com/CikiMomogi/website/pull/11)
- [x] [middleware.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/middleware.md) => [PR](https://github.com/CikiMomogi/website/pull/18)
- [x] [README.md](https://github.com/grammyjs/website/blob/main/site/docs/guide/README.md) => [PR#1](https://github.com/CikiMomogi/website/pull/10), [PR#2](https://github.com/CikiMomogi-grammY/website/pull/67)

## Hosting
- [x] [comparison.md](https://github.com/grammyjs/website/blob/main/site/docs/hosting/comparison.md) => [PR](https://github.com/CikiMomogi-grammY/website/pull/59)
- [x] [deno-deploy.md](https://github.com/grammyjs/website/blob/main/site/docs/hosting/deno-deploy.md) => [PR](https://github.com/CikiMomogi-grammY/website/pull/60)
- [x] [gcf.md](https://github.com/grammyjs/website/blob/main/site/docs/hosting/gcf.md) => [PR](https://github.com/CikiMomogi-grammY/website/pull/61)
- [x] [heroku.md](https://github.com/grammyjs/website/blob/main/site/docs/hosting/heroku.md) => [PR](https://github.com/CikiMomogi-grammY/website/pull/62)
- [x] [supabase.md](https://github.com/grammyjs/website/blob/main/site/docs/hosting/supabase.md) => [PR](https://github.com/CikiMomogi-grammY/website/pull/64)
- [x] [vps.md](https://github.com/grammyjs/website/blob/main/site/docs/hosting/vps.md) => [PR](https://github.com/CikiMomogi-grammY/website/pull/63)

## Plugins
- [x] [auto-retry.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/auto-retry.md) => [PR](https://github.com/CikiMomogi/website/pull/40)
- [x] [autoquote.md](https://github.com/grammyjs/website/pull/441) => [PR](https://github.com/CikiMomogi-grammY/website/pull/70)
- [x] [command-filter.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/command-filter.md) => [PR](https://github.com/CikiMomogi/website/pull/49)
- [x] [console-time.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/console-time.md) => [PR](https://github.com/CikiMomogi/website/pull/50)
- [x] [conversations.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/conversations.md) => [PR](https://github.com/CikiMomogi-grammY/website/pull/69)
- [x] [emoji.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/emoji.md) => [PR](https://github.com/CikiMomogi/website/pull/47)
- [x] [files.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/files.md) => [PR](https://github.com/CikiMomogi/website/pull/43)
- [x] [fluent.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/fluent.md) => [PR](https://github.com/CikiMomogi/website/pull/44)
- [x] [guide.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/guide.md) => [PR](https://github.com/CikiMomogi/website/pull/33)
- [x] [hydrate.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/hydrate.md) => [PR](https://github.com/CikiMomogi/website/pull/39)
- [x] [i18n.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/i18n.md) => [PR](https://github.com/CikiMomogi-grammY/website/pull/58)
- [x] [keyboard.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/keyboard.md) => [PR](https://github.com/CikiMomogi/website/pull/35)
- [x] [menu.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/menu.md) => [PR](https://github.com/CikiMomogi/website/pull/36)
- [x] [middlewares.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/middlewares.md) => [PR](https://github.com/CikiMomogi/website/pull/51)
- [x] [parse-mode.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/parse-mode.md) => [PR](https://github.com/CikiMomogi/website/pull/48)
- [x] [ratelimiter.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/ratelimiter.md) => [PR](https://github.com/CikiMomogi/website/pull/42)
- [x] [README.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/README.md) => [PR](https://github.com/CikiMomogi/website/pull/32)
- [x] [router.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/router.md) => [PR](https://github.com/CikiMomogi/website/pull/45)
- [x] [runner.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/runner.md) => [PR](https://github.com/CikiMomogi/website/pull/38)
- [x] [session.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/session.md) => [PR](https://github.com/CikiMomogi/website/pull/34)
- [x] [stateless-question.md](https://github.com/grammyjs/website/blob/main/site/docs/plugins/stateless-question.md) => [PR](https://github.com/CikiMomogi/website/pull/37)
- [x] [transformer-throttler.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/transformer-throttler.md) => [PR](https://github.com/CikiMomogi/website/pull/41)

## Resources
- [x] [about.md](https://github.com/grammyjs/website/blob/main/site/docs/resources/about.md) => [PR](https://github.com/CikiMomogi/website/pull/52)
- [x] [comparison.md](https://github.com/grammyjs/website/blob/main/site/docs/resources/comparison.md) => [PR](https://github.com/CikiMomogi-grammY/website/pull/57)
- [x] [faq.md](https://github.com/grammyjs/website/blob/main/site/docs/resources/faq.md) => [PR](https://github.com/CikiMomogi-grammY/website/pull/56)

## Config
- [x] Project title and description, navbar, search bar, etc => https://github.com/CikiMomogi/website/pull/6

**Comment by KnorpelSenf** [comment]
@CikiMomogi so cool to see you're attempting to translate the website to Indonesian! This is a huge effort that should not be underestimated. I hope you are familiar with [the translation guide](https://github.com/grammyjs/website/blob/main/TRANSLATING.md) :)

We are going to follow your progress closely so we can be sure that the translations are of high quality. Could you tell us the names of all contributors known so far who are going to help you translate this page to Indonesian? A rough estimate is that the translation will take 250-400 work hours, so even if you spent 50 hours per week, it will take more than one month. This is based on how much time the last teams needed.

Having someone to review and reiterate is very important because clear language should always be validated by another person to be truly understandable.

**Comment by CikiMomogi** [comment]
> @CikiMomogi so cool to see you're attempting to translate the website to Indonesian! This is a huge effort that should not be underestimated. I hope you are familiar with [the translation guide](https://github.com/grammyjs/website/blob/main/TRANSLATING.md) :)

Thanks for the kind words. I've read translation guide and understand that this is a long time-consuming project, should be fully completed, and has potential to be abandoned. I will do my best to complete this project. 

For the translation quality, I have some experience translating various applications (you can check my crowdin `@CikiMomogi`). I always choose the word that are easier to understand and not too technical for my fellow Indonesian out there without compromising the meaning of the sentence itself. Not just copy-paste from the translator.

For now I do not have a list of other contributors. Of course, I look forward to readers who are fluent in Indonesian to contribute as well.

**Comment by roj1512** [comment]
Hi there @CikiMomogi!

---

We want to keep the current quality of our documentation, we want our upcoming translations in other languages to be simple, clear, and easily understandable by the speakers of the respective language.

To ensure and enforce a high-quality translation, we need each page to be reviewed individually after it has been translated.
To do that, you will have to open a pull request for each page that you translate.
All of those pull requests should be reviewed.
We recommend the reviews are done by someone else than the one who translated the page, but this can be done by the one who translated if there was no chance to have someone else.

---

Here are some suggestions for your translation process:

- To make your translations always stay up-to-date, subscribe to pull request notifications on this repository (Watch > Custom > Pull requests > Apply), and watch out for pull requests that might get the "ready for translation" label. Once they have this label, you can sync your translations with the changes that the pull request suggests. This is only if you have previously translated the page that the pull request is meant for.
- Always keep a browser window open for previewing the pages while you translate them. See how you can [run the website locally](https://github.com/grammyjs/website#building-the-website-locally).
- [Format](https://github.com/grammyjs/website#checking-correct-formatting-of-docs) the files often.
- While translating the pages, keep mind that you should not leave the anchor links (for example `#indonesian-language`) as they are. They should be replaced with the translated section name (for example if the translated section name is "Bahasa Indonesia", it should be replaced with "#bahasa-indonesia").

---

Feel free to ask me questions or to tell me if a point needs more clarification. Thank you for your efforts!

**Comment by CikiMomogi** [comment]
After I merged https://github.com/grammyjs/website/pull/375  into my main branch, I got an error when running `npm run docs:dev`.  Can anyone help me? Here is the error log:
```
> grammy-website@1.0.0 docs:dev
> vuepress-vite dev docs
​
Error: Cannot find module './index.json'
Require stack:
- /home/qz/development/grammY/web/website/site/docs/.vuepress/plugins/current-versions/plugin.ts
- /home/qz/development/grammY/web/website/site/docs/.vuepress/config.ts
- /home/qz/development/grammY/web/website/site/node_modules/@vuepress/cli/lib/config/loadUserConfigCjs.js
- /home/qz/development/grammY/web/website/site/node_modules/@vuepress/cli/lib/config/loadUserConfig.js
- /home/qz/development/grammY/web/website/site/node_modules/@vuepress/cli/lib/config/index.js
- /home/qz/development/grammY/web/website/site/node_modules/@vuepress/cli/lib/commands/build/createBuild.js
- /home/qz/development/grammY/web/website/site/node_modules/@vuepress/cli/lib/commands/build/index.js
- /home/qz/development/grammY/web/website/site/node_modules/@vuepress/cli/lib/commands/index.js
- /home/qz/development/grammY/web/website/site/node_modules/@vuepress/cli/lib/index.js
- /home/qz/development/grammY/web/website/site/node_modules/vuepress-vite/bin/vuepress.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/qz/development/grammY/web/website/site/docs/.vuepress/plugins/current-versions/plugin.ts:26:28)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.require.extensions..ts (/home/qz/development/grammY/web/website/site/node_modules/@vuepress/cli/lib/utils/allowTs.js:11:11)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by KnorpelSenf** [comment]
You need to run `npm install` one more time.

This will make sure that `npm run docs:index-versions` is executed, a script that generates a local index or all most recent plugin versions. (So you could also just run the latter script manually.)

**Comment by CikiMomogi** [comment]
The error was resolved after I ran `npm run docs:index-versions`. Thanks for the help.

**Comment by CikiMomogi** [comment]
Regarding point 1 of the [following page](http://grammy.dev/guide/context.html#available-actions),

> 1. We must have access to the bot object. This means that we have to pass the bot object all around our code base in order to respond, which is annoying when you have more than one source file and you define your listener somewhere else.

I understand that we can use `ctx.api `instead of `bot.api.` That way, we no longer need to pass the bot object around the code base, right? But I don't quite understand the use case. Can you give an example or source code of comparison between the two?

**Comment by KnorpelSenf** [comment]
The train of thought is:

Need to use `bot.api` for every API call
 → need access to `bot` in everywhere
 → need to import it into every module
 → results in high cohesion of the source
 → prevents us from decoupling our components
 → bad software architecture.

So the solution is to use `ctx.api` because the `ctx` is declared locally in every module, so you can decouple your code and have a good architecture.

That's simplified, but you get the idea.

**Comment by CikiMomogi** [comment]
After I read some [source code examples](https://github.com/grammyjs/awesome-grammY), now I completely understood. Previously, I had confused `ctx.api` with `composer` to replace the `bot` object. :P

**Comment by CikiMomogi** [comment]
@sensen: 
I am going to return the translation for some technical words to their origin, e.g:
`kueri inline` => `inline query`, 
`penggerak grammY` => `grammy runner`,
`pembaruan` => `update` (update object),
`komposer` => `composer`
`permintaan` => `request` (HTTP request)
etc.

However, commonly used phrases will remain:
`composer class` => `kelas composer`
`function x` => `fungsi x`, 
etc.

I'm pretty sure the readers have learned programming before, therefore they should be familiar with these words. Moreover, the words when translated sound a little weird - at least for me. I want to hear your thoughts on whether this is a good idea.

**Comment by sensen** [comment]
Hey @CikiMomogi!

I agree. It sounds weird to me, too. Possibly because we're very familiar with the English words.

I can't remember the last timeI read documentation in Indonesian language. But if I were to do that, I'd prefer the documentation to keep the technical terms in English.

If you decided to go with this, I'd suggest not translating even `composer class` or `function x`.

**Comment by CikiMomogi** [comment]
Can I change the link reference from Deno
https://github.com/grammyjs/website/blob/0565e6b4fc21016daff8f703b6e27252ae9afc08/site/docs/guide/deployment-types.md?plain=1#L152

to here?
https://github.com/grammyjs/website/blob/0565e6b4fc21016daff8f703b6e27252ae9afc08/site/docs/guide/deployment-types.md?plain=1#L235

Since the content is the same, I think it would be better to redirect readers to the translated doc instead.

**Comment by KnorpelSenf** [comment]
> Can I change the link reference from Deno
> 
> https://github.com/grammyjs/website/blob/0565e6b4fc21016daff8f703b6e27252ae9afc08/site/docs/guide/deployment-types.md?plain=1#L152
> 
> to here?
> 
> https://github.com/grammyjs/website/blob/0565e6b4fc21016daff8f703b6e27252ae9afc08/site/docs/guide/deployment-types.md?plain=1#L235
> 
> Since the content is the same, I think it would be better to redirect readers to the translated doc instead.

There are two links in the line of text you reference, and one of them already refers to https://github.com/grammyjs/website/blob/0565e6b4fc21016daff8f703b6e27252ae9afc08/site/docs/guide/deployment-types.md?plain=1#L235 if I'm not mistaken.

**Comment by CikiMomogi** [comment]
Well, I can rearrange the words to reference the same link. But, I wonder if you did them intentionally, except for avoiding the same link in the same sentence.

**Comment by CikiMomogi** [comment]
> I have opened #418 which fixes the problem. Can you check it out and say if that phrasing is better?

Yep, looks good to me!

**Comment by CikiMomogi** [comment]
Is `Node` in the comment bellow referring to node.js? If so, does that mean there is a typo in the code snippet for Deno? ([full context](https://grammy.dev/advanced/reliability.html#graceful-shutdown))

```js
const { Bot } = require("grammy");

const bot = new Bot("<token>");

// Stopping the bot when Node process
// is about to be terminated
process.once("SIGINT", () => bot.stop());
process.once("SIGTERM", () => bot.stop());

await bot.start();
```

Deno:

```ts
import { Bot } from "https://deno.land/x/grammy/mod.ts";
import { run } from "https://deno.land/x/grammy_runner/mod.ts";

const bot = new Bot("<token>");

const runner = run(bot);

// Stopping the bot when Node process
// is about to be terminated
const stopRunner = () => runner.isRunning() && runner.stop();
Deno.addSignalListener("SIGINT", stopRunner);
Deno.addSignalListener("SIGTERM", stopRunner);

**Comment by roj1512** [comment]
Thank you for the report, @CikiMomogi!

I've opened #421 related to that, can you please do me a review?

**Comment by CikiMomogi** [comment]
Don't we need to import `somePluginMethod` from `some-plugin` because we invoke `bot.api.somePluginMethod()` on line 109?

https://github.com/grammyjs/website/blob/2d7ba3b9a9311aa8b2244cb46048dadb6412e613/site/docs/advanced/transformers.md?plain=1#L93-L113

**Comment by roj1512** [comment]
No, `somePluginMethod` is a method that will be added to bot.api’s prototype after the plugin is installed in line 106.

**Comment by CikiMomogi** [comment]
Can somebody please check [my PQ](https://github.com/CikiMomogi/website/pull/33)? The github actions keep failing. However, when I ran `deno fmt --check`, there was no such error. Somehow the formatting error was found in another file that I haven't touched at all.

**Comment by KnorpelSenf** [comment]
This is because of the recent Deno 1.23.0 update. Look how https://github.com/denoland/deno/pull/14841 was merged and now affects existing files in all future CI runs. Feel free to fix it, even though that means you'll touch unrelated files.

@roj1512 it would be great if you could push a formatting commit upstream.

**Comment by CikiMomogi** [comment]
Oh, so that's the reason. I guess it's perfect time to upgrade my Deno.

**Comment by roj1512** [comment]
@KnorpelSenf I don't have access to his fork.

**Comment by KnorpelSenf** [comment]
I guess that's the disadvantage of doing translations in forks.

Do you need write access for anything, i.e. is there anything you can't do via forking? Should I ask @CikiMomogi to give you write access? :smile:

**Comment by roj1512** [comment]
Of course I can make a PR to reformat. I thought you mean I just push to his upstream

**Comment by KnorpelSenf** [comment]
Ah I see, sorry, I meant the main repo, but now I fixed it myself in https://github.com/grammyjs/website/pull/422

**Comment by KnorpelSenf** [comment]
I should've maybe referred back to https://github.com/grammyjs/website/issues/369#issuecomment-1157306824 from #422 🤔

**Comment by CikiMomogi** [comment]
I'm a bit lost as to what `creator` means here. My interpretation is that `ctx.match` will contain the name of the message sender, **NOT** the creator of the bot. So, the bot will reply "I was created by (message sender name)", correct? 

Moreover, why even bother storing the payload if we can just fetch the name of the message sender directly from `ctx.from.first_name` from context object.

https://github.com/grammyjs/website/blob/f223bafa619e6c7e56787308c3deab9d81b76777/site/docs/plugins/menu.md?plain=1#L313-L331

**Comment by KnorpelSenf** [comment]
Creator refers to the original author of the message, also across forwards. While we could clarify that, it's also a very primitive example to illustrate the feature without much code. Maybe we can find a real-world use case that is better suited as an example to explain this. Do you have any suggestions?

**Comment by CikiMomogi** [comment]
Page not found at the following link:

https://github.com/grammyjs/website/blob/748e38dd10b9dfd01f8d03dbd0a10048159ff67c/site/docs/plugins/auto-retry.md?plain=1#L75

Is it supposed to reference this link, https://raw.githubusercontent.com/grammyjs/auto-retry/main/src/index.ts?

**Comment by KnorpelSenf** [comment]
https://doc.deno.land/https://raw.githubusercontent.com/grammyjs/auto-retry/main/src/index.ts is the correct link. Deno changed something in the way they represent their URLs, which broke this link. It used to work before.

**Comment by CikiMomogi** [comment]
Got it! I will make the PQ.

**Comment by CikiMomogi** [comment]
@KnorpelSenf @roj1512 Do you guys need a review approval for each pull request in my repository? Currently I have approval enabled only for one reviewer.

**Comment by roj1512** [comment]
@CikiMomogi nope, it's fine!

**Comment by CikiMomogi** [comment]
https://github.com/grammyjs/website/blob/f1bc5343e90491f89b8444e4ae8bfe27ff53e656/site/docs/resources/comparison.md?plain=1#L41-L43

What is `(=editor support)` at the end of line 43? Does it have a specific meaning or is it just a typo?

**Comment by KnorpelSenf** [comment]
Types give information about the code to the editor. That's why providing types improves how well your editor can support you. Types equals editor support.

**Comment by CikiMomogi** [comment]
Is the editor here referring to the code editor? Therefore, by providing types, it can bring more information to the code editor and thus improve productivity.

**Comment by KnorpelSenf** [comment]
Yes, the TypeScript types improve what VSCode can do for you. We describe this in more depth a few paragraphs later.

**Comment by CikiMomogi** [comment]
https://github.com/orgs/CikiMomogi-grammY/teams/translator/discussions/3/comments/8
> CSS untuk dokumentasinya, memang dibuat pakai text-justify: inter-character ya? kadang agak ngerasain pada bagian tertentu paragrafnya jadi kayak A B C D.
>
> ![](https://user-images.githubusercontent.com/109416385/182292438-cad6405e-f56a-4744-899c-47050d31f7e9.png)
> ![](https://user-images.githubusercontent.com/109416385/182292458-045db202-91f0-4558-9c94-1ef4ab4390da.png)

_"Does the CSS intentionally use `text-justify: inter-character`? The spacing in some paragraphs looks too wide if the words are too long"._ Is it possible for us to fix the issue?

**Comment by KnorpelSenf** [comment]
Yes, all styles are here: https://github.com/grammyjs/website/blob/2ffcde510a7e25d9bbf72c889c4344b249c8e473/site/docs/.vuepress/styles/index.scss#L36

Feel free to play around with the config. For example, it looks like your browser isn't able to hyphenate Indonesian. This issue does not appear in English.
