### ISSUE TITLE
Russian translation tracking

### ISSUE THREAD

**Issue by evermake** [grammyjs/website#620]
This issue is for tracking the translation progress of all pages. It will be closed when the translation of the whole documentation is finished.

### Before translating
- Before you start, read the [translation guide](https://github.com/grammyjs/website/blob/main/TRANSLATING.md)
- Pick one untranslated page from the list below and start translating it locally

### While translating
- **DO NOT** just copy the translation from some translator tool, use your own native-speaker skills

### After translating
- Create PR from your fork against the [`ru`](https://github.com/grammyjs/website/tree/ru) branch

### Landing Page and Config

- [ ] [README.md](../tree/main/site/docs/README.md) (waiting for [review](../tree/ru/site/docs/ru/README.md))
- [ ] [config.ts](../tree/main/site/docs/.vuepress/config.ts)

#### Guide

- [ ] [README.md](../tree/main/site/docs/guide/README.md)
- [ ] [introduction.md](../tree/main/site/docs/guide/introduction.md) (waiting for [review](https://github.com/grammyjs/website/pull/647))
- [ ] [getting-started.md](../tree/main/site/docs/guide/getting-started.md)
- [ ] [basics.md](../tree/main/site/docs/guide/basics.md)
- [ ] [context.md](../tree/main/site/docs/guide/context.md)
- [ ] [api.md](../tree/main/site/docs/guide/api.md)
- [ ] [filter-queries.md](../tree/main/site/docs/guide/filter-queries.md)
- [ ] [commands.md](../tree/main/site/docs/guide/commands.md)
- [ ] [middleware.md](../tree/main/site/docs/guide/middleware.md)
- [ ] [errors.md](../tree/main/site/docs/guide/errors.md)
- [ ] [inline-queries.md](../tree/main/site/docs/guide/inline-queries.md)
- [ ] [files.md](../tree/main/site/docs/guide/files.md)
- [ ] [games.md](../tree/main/site/docs/guide/games.md)
- [ ] [deployment-types.md](../tree/main/site/docs/guide/deployment-types.md)

#### Advanced

- [ ] [README.md](../tree/main/site/docs/advanced/README.md)
- [ ] [middleware.md](../tree/main/site/docs/advanced/middleware.md)
- [ ] [structuring.md](../tree/main/site/docs/advanced/structuring.md)
- [ ] [scaling.md](../tree/main/site/docs/advanced/scaling.md)
- [ ] [reliability.md](../tree/main/site/docs/advanced/reliability.md)
- [ ] [flood.md](../tree/main/site/docs/advanced/flood.md)
- [ ] [transformers.md](../tree/main/site/docs/advanced/transformers.md)
- [ ] [proxy.md](../tree/main/site/docs/advanced/proxy.md)
- [ ] [deployment.md](../tree/main/site/docs/advanced/deployment.md)

#### Introduction

- [ ] [README.md](../tree/main/site/docs/plugins/README.md)
- [ ] [guide.md](../tree/main/site/docs/plugins/guide.md)

#### Built-in

- [ ] [session.md](../tree/main/site/docs/plugins/session.md)
- [ ] [keyboard.md](../tree/main/site/docs/plugins/keyboard.md)

#### Official

- [ ] [conversations.md](../tree/main/site/docs/plugins/conversations.md)
- [ ] [menu.md](../tree/main/site/docs/plugins/menu.md)
- [ ] [stateless-question.md](../tree/main/site/docs/plugins/stateless-question.md)
- [ ] [runner.md](../tree/main/site/docs/plugins/runner.md)
- [ ] [hydrate.md](../tree/main/site/docs/plugins/hydrate.md)
- [ ] [auto-retry.md](../tree/main/site/docs/plugins/auto-retry.md)
- [ ] [transformer-throttler.md](../tree/main/site/docs/plugins/transformer-throttler.md)
- [ ] [ratelimiter.md](../tree/main/site/docs/plugins/ratelimiter.md)
- [ ] [files.md](../tree/main/site/docs/plugins/files.md)
- [ ] [i18n.md](../tree/main/site/docs/plugins/i18n.md)
- [ ] [fluent.md](../tree/main/site/docs/plugins/fluent.md)
- [ ] [router.md](../tree/main/site/docs/plugins/router.md)
- [ ] [emoji.md](../tree/main/site/docs/plugins/emoji.md)
- [ ] [parse-mode.md](../tree/main/site/docs/plugins/parse-mode.md)

#### Third-party

- [ ] [console-time.md](../tree/main/site/docs/plugins/console-time.md)
- [ ] [middlewares.md](../tree/main/site/docs/plugins/middlewares.md)
- [ ] [autoquote.md](../tree/main/site/docs/plugins/autoquote.md)

#### grammY

- [ ] [about.md](../tree/main/site/docs/resources/about.md) (waiting for [review](https://github.com/grammyjs/website/pull/622))
- [ ] [faq.md](../tree/main/site/docs/resources/faq.md)
- [ ] [comparison.md](../tree/main/site/docs/resources/comparison.md)

#### Overview

- [ ] [comparison.md](../tree/main/site/docs/hosting/comparison.md)

#### Tutorials

- [ ] [deno-deploy.md](../tree/main/site/docs/hosting/deno-deploy.md)
- [ ] [supabase.md](../tree/main/site/docs/hosting/supabase.md)
- [ ] [heroku.md](../tree/main/site/docs/hosting/heroku.md)
- [ ] [fly.md](../tree/main/site/docs/hosting/fly.md)
- [ ] [vercel.md](../tree/main/site/docs/hosting/vercel.md)
- [ ] [vps.md](../tree/main/site/docs/hosting/vps.md)

**Comment by roj1512** [comment]
Лукинг форуард, друзя!

**Comment by KnorpelSenf** [comment]
@evermake are there any updates on this?

**Comment by evermake** [comment]
> @evermake are there any updates on this?

Hi, I'm working on it locally, going to upload couple of pages this Sunday.

**Comment by KnorpelSenf** [comment]
These translations seem to have stalled. Should we close this and all linked PQs?

In case someone wants to pick it up again in the future, it will be easy to restore all work.
