### ISSUE TITLE
Ukrainian translation tracking

### ISSUE THREAD

**Issue by Nazar-Ant** [grammyjs/website#638]
This issue is for tracking the translation progress of all pages. It will be closed when the translation of the whole documentation is finished.

### Before translating
- Before you start, read the [translation guide](https://github.com/grammyjs/website/blob/main/TRANSLATING.md)
- Pick one untranslated page from the list below and start translating it locally

### While translating
- **DO NOT** just copy the translation from some translator tool, use your own native-speaker skills

### After translating
- Create PR from your fork against the [`uk`](https://github.com/grammyjs/website/tree/uk) branch

### Landing Page and Config

- [x] [README.md](../tree/main/site/docs/README.md)
- [x] [config.ts](../tree/main/site/docs/.vuepress/config.ts)

#### Guide

- [x] [README.md](../tree/main/site/docs/guide/README.md)
- [x] [introduction.md](../tree/main/site/docs/guide/introduction.md)
- [x] [getting-started.md](../tree/main/site/docs/guide/getting-started.md)
- [x] [basics.md](../tree/main/site/docs/guide/basics.md)
- [x] [context.md](../tree/main/site/docs/guide/context.md)
- [x] [api.md](../tree/main/site/docs/guide/api.md)
- [x] [filter-queries.md](../tree/main/site/docs/guide/filter-queries.md)
- [x] [commands.md](../tree/main/site/docs/guide/commands.md)
- [x] [middleware.md](../tree/main/site/docs/guide/middleware.md)
- [x] [errors.md](../tree/main/site/docs/guide/errors.md)
- [x] [inline-queries.md](../tree/main/site/docs/guide/inline-queries.md)
- [x] [files.md](../tree/main/site/docs/guide/files.md)
- [x] [games.md](../tree/main/site/docs/guide/games.md)
- [x] [deployment-types.md](../tree/main/site/docs/guide/deployment-types.md)

#### Advanced

- [x] [README.md](../tree/main/site/docs/advanced/README.md)
- [x] [middleware.md](../tree/main/site/docs/advanced/middleware.md)
- [x] [structuring.md](../tree/main/site/docs/advanced/structuring.md)
- [x] [scaling.md](../tree/main/site/docs/advanced/scaling.md)
- [x] [reliability.md](../tree/main/site/docs/advanced/reliability.md)
- [x] [flood.md](../tree/main/site/docs/advanced/flood.md)
- [x] [transformers.md](../tree/main/site/docs/advanced/transformers.md)
- [x] [proxy.md](../tree/main/site/docs/advanced/proxy.md)
- [x] [deployment.md](../tree/main/site/docs/advanced/deployment.md)

#### Introduction

- [x] [README.md](../tree/main/site/docs/plugins/README.md)
- [x] [guide.md](../tree/main/site/docs/plugins/guide.md)

#### Built-in

- [x] [session.md](../tree/main/site/docs/plugins/session.md)
- [x] [keyboard.md](../tree/main/site/docs/plugins/keyboard.md)

#### Official

- [x] [conversations.md](../tree/main/site/docs/plugins/conversations.md)
- [x] [menu.md](../tree/main/site/docs/plugins/menu.md)
- [x] [stateless-question.md](../tree/main/site/docs/plugins/stateless-question.md)
- [x] [runner.md](../tree/main/site/docs/plugins/runner.md)
- [x] [hydrate.md](../tree/main/site/docs/plugins/hydrate.md)
- [x] [auto-retry.md](../tree/main/site/docs/plugins/auto-retry.md)
- [x] [transformer-throttler.md](../tree/main/site/docs/plugins/transformer-throttler.md)
- [x] [ratelimiter.md](../tree/main/site/docs/plugins/ratelimiter.md)
- [x] [files.md](../tree/main/site/docs/plugins/files.md)
- [x] [i18n.md](../tree/main/site/docs/plugins/i18n.md)
- [x] [fluent.md](../tree/main/site/docs/plugins/fluent.md)
- [x] [router.md](../tree/main/site/docs/plugins/router.md)
- [x] [emoji.md](../tree/main/site/docs/plugins/emoji.md)
- [x] [parse-mode.md](../tree/main/site/docs/plugins/parse-mode.md)
- [x] [chat-members.md](../tree/main/site/docs/plugins/chat-members.md)

#### Third-party

- [x] [console-time.md](../tree/main/site/docs/plugins/console-time.md)
- [x] [middlewares.md](../tree/main/site/docs/plugins/middlewares.md)
- [x] [autoquote.md](../tree/main/site/docs/plugins/autoquote.md)

#### grammY

- [x] [about.md](../tree/main/site/docs/resources/about.md)
- [x] [faq.md](../tree/main/site/docs/resources/faq.md)
- [x] [comparison.md](../tree/main/site/docs/resources/comparison.md)

#### Overview

- [x] [comparison.md](../tree/main/site/docs/hosting/comparison.md)

#### Tutorials

- [x] [deno-deploy.md](../tree/main/site/docs/hosting/deno-deploy.md)
- [x] [supabase.md](../tree/main/site/docs/hosting/supabase.md)
- [x] [cloudflare-workers.md](../tree/main/site/docs/hosting/cloudflare-workers.md)
- [x] [heroku.md](../tree/main/site/docs/hosting/heroku.md)
- [x] [fly.md](../tree/main/site/docs/hosting/fly.md)
- [x] [firebase.md](../tree/main/site/docs/hosting/firebase.md)
- [x] [gcf.md](../tree/main/site/docs/hosting/gcf.md)
- [x] [vercel.md](../tree/main/site/docs/hosting/vercel.md)
- [x] [vps.md](../tree/main/site/docs/hosting/vps.md)

**Comment by KnorpelSenf** [comment]
How on earth are you guys so fast, that's some superhuman pace right there

**Comment by Nazar-Ant** [comment]
@KnorpelSenf Thank you for your praise. Fortunately, I have plenty of time.

**Comment by KnorpelSenf** [comment]
I can see that, it's quite impressive

**Comment by Nazar-Ant** [comment]
@roj1512 That's so nice of you :kissing_heart:

**Comment by roj1512** [comment]
59.6% in about half a month, congrats to you!

**Comment by LWJerri** [comment]
> 59.6% in about half a month, congrats to you!

Yeap, @Nazar-Ant is working very hard on the translation. @deptyped and I haven't been very active in the last week because of our own lives, but we are still trying to do the translation. I also updated the files I translated, so the % here is already higher than 59.6))

**Comment by LWJerri** [comment]
> 59.6% in about half a month, congrats to you!

What about 79.66%?

**Comment by roj1512** [comment]
Brrrrrrr

**Comment by KnorpelSenf** [comment]
Just 10 more pages 😱

**Comment by roj1512** [comment]
Vrrrrrrrrrrrrrrrrrrrrrrrrrrrr

**Comment by KnorpelSenf** [comment]
fucking finally
