### ISSUE TITLE
Italian translation tracking

### ISSUE THREAD

**Issue by Anulo2** [grammyjs/website#707]
This issue is for tracking the translation progress of all pages. It will be closed when the translation of the whole documentation is finished.
### Before translating

-   Before you start, read the [translation guide](https://github.com/grammyjs/website/blob/main/TRANSLATING.md)
-  Pick one untranslated page from the list below and start translating it locally

### While translating

- **DO NOT** just copy the translation from some translator tool, use your own native-speaker skills

### After translating

 - Create PR from your fork against the [it](https://github.com/grammyjs/website/tree/it) branch

### Landing Page and Config

- [ ] [README.md](https://github.com/grammyjs/website/tree/main/site/docs/README.md)
- [ ]  [config.ts](https://github.com/grammyjs/website/tree/main/site/docs/.vuepress/config.ts)

#### Guide

- [ ] [README.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/README.md)
- [ ] [introduction.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/introduction.md)
- [ ] [getting-started.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/getting-started.md)
- [ ] [basics.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/basics.md)
- [ ] [context.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/context.md)
- [ ] [api.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/api.md)
- [ ] [filter-queries.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/filter-queries.md)
- [ ] [commands.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/commands.md)
- [ ] [middleware.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/middleware.md)
- [ ] [errors.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/errors.md)
- [ ] [inline-queries.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/inline-queries.md)
- [ ] [files.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/files.md)
- [ ] [games.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/games.md)
- [ ] [deployment-types.md](https://github.com/grammyjs/website/tree/main/site/docs/guide/deployment-types.md)

#### Advanced

- [ ] [README.md](https://github.com/grammyjs/website/tree/main/site/docs/advanced/README.md)
- [x] [middleware.md](https://github.com/grammyjs/website/tree/main/site/docs/advanced/middleware.md)
- [ ] [structuring.md](https://github.com/grammyjs/website/tree/main/site/docs/advanced/structuring.md)
- [ ] [scaling.md](https://github.com/grammyjs/website/tree/main/site/docs/advanced/scaling.md)
- [x] [reliability.md](https://github.com/grammyjs/website/tree/main/site/docs/advanced/reliability.md)
- [x] [flood.md](https://github.com/grammyjs/website/tree/main/site/docs/advanced/flood.md)
- [ ] [transformers.md](https://github.com/grammyjs/website/tree/main/site/docs/advanced/transformers.md)
- [x] [proxy.md](https://github.com/grammyjs/website/tree/main/site/docs/advanced/proxy.md)
 - [x] [deployment.md](https://github.com/grammyjs/website/tree/main/site/docs/advanced/deployment.md)

#### Introduction

- [ ] [README.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/README.md)
- [ ] [guide.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/guide.md)

#### Built-in

- [ ] [session.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/session.md)
- [ ] [keyboard.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/keyboard.md)

#### Official

- [ ] [conversations.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/conversations.md)
- [ ] [menu.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/menu.md)
- [ ] [stateless-question.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/stateless-question.md)
- [ ] [runner.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/runner.md)
- [ ] [hydrate.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/hydrate.md)
- [ ] [auto-retry.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/auto-retry.md)
- [ ] [transformer-throttler.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/transformer-throttler.md)
- [ ] [ratelimiter.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/ratelimiter.md)
- [ ] [files.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/files.md)
- [ ] [i18n.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/i18n.md)
- [ ] [fluent.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/fluent.md)
- [ ] [router.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/router.md)
- [ ] [emoji.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/emoji.md)
- [ ] [parse-mode.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/parse-mode.md)
- [ ] [chat-members.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/chat-members.md)

#### Third-party

- [ ] [console-time.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/console-time.md)
- [ ] [middlewares.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/middlewares.md)
 - [ ] [autoquote.md](https://github.com/grammyjs/website/tree/main/site/docs/plugins/autoquote.md)

#### grammY

- [ ] [about.md](https://github.com/grammyjs/website/tree/main/site/docs/resources/about.md)
- [ ] [faq.md](https://github.com/grammyjs/website/tree/main/site/docs/resources/faq.md)
- [ ] [comparison.md](https://github.com/grammyjs/website/tree/main/site/docs/resources/comparison.md)

#### Overview

 - [ ] [comparison.md](https://github.com/grammyjs/website/tree/main/site/docs/hosting/comparison.md)

#### Tutorials

- [ ] [deno-deploy.md](https://github.com/grammyjs/website/tree/main/site/docs/hosting/deno-deploy.md)
- [ ] [supabase.md](https://github.com/grammyjs/website/tree/main/site/docs/hosting/supabase.md)
- [ ] [heroku.md](https://github.com/grammyjs/website/tree/main/site/docs/hosting/heroku.md)
- [ ] [fly.md](https://github.com/grammyjs/website/tree/main/site/docs/hosting/fly.md)
- [ ] [vercel.md](https://github.com/grammyjs/website/tree/main/site/docs/hosting/vercel.md)
- [ ] [vps.md](https://github.com/grammyjs/website/tree/main/site/docs/hosting/vps.md)

**Comment by Anulo2** [comment]
Update about the italian translation status: It is currenty on hold as you can see from the commits but will hopefully resume in 2 months or so. That's because in the following month and a half I will be at various local conferences and events with many people in the open source community and will try to get as many people as possible interested in grammy and the effort of translating the site. If I will be able find some people to help me out I will post a comment here, until then, let's hope for the best :D

**Comment by KnorpelSenf** [comment]
It seems like the translations here have stalled. Can I assume that you have lost interest? Since you didn't leave a comment about new people who want to join in, is it just that you did not find anyone?

If your current focus is not on the translations and you no longer are keen on working on this, we will close this issue in the coming days. Naturally, it can always be picked up again in the future.

**Comment by Anulo2** [comment]
> It seems like the translations here have stalled. Can I assume that you have lost interest? Since you didn't leave a comment about new people who want to join in, is it just that you did not find anyone?
> 
> If your current focus is not on the translations and you no longer are keen on working on this, we will close this issue in the coming days. Naturally, it can always be picked up again in the future.

Hey there, I've not lost insterest but unfortunately I've not found enough people to work on the translation, if in the future there are new contributors that want to do the italian translation feel free to ping me on Telegram (@Anulo2SecondoAcc), I would love to help :D
