### ISSUE TITLE
Portuguese (Brazil) translation tracking

### ISSUE THREAD

**Issue by kr4t0z** [grammyjs/website#884]
This issue is for tracking the translation progress of all pages. It will be closed when the translation of the whole documentation is finished.

### Before translating

- Before you start, read the [translation guide](https://github.com/grammyjs/website/blob/main/TRANSLATING.md)
- Pick one untranslated page from the list below and start translating it locally

### While translating

- **DO NOT** just copy the translation from some translator tool, use your own native-speaker skills

### After translating

- Create PR from your fork against the [`pt`](https://github.com/grammyjs/website/tree/pt) branch

### Landing Page and Config

- [x] [README.md](../tree/main/site/docs/README.md)
- [x] [config.ts](https://github.com/grammyjs/website/blob/main/site/docs/.vitepress/config.ts)
- [x] [locale](https://github.com/grammyjs/website/blob/main/site/docs/.vitepress/configs/locales/en.ts)

#### Guide

- [x] [README.md](../tree/main/site/docs/guide/README.md)
- [x] [introduction.md](../tree/main/site/docs/guide/introduction.md)
- [x] [getting-started.md](../tree/main/site/docs/guide/getting-started.md)
- [x] [basics.md](../tree/main/site/docs/guide/basics.md)
- [x] [context.md](../tree/main/site/docs/guide/context.md)
- [x] [api.md](../tree/main/site/docs/guide/api.md)
- [x] [filter-queries.md](../tree/main/site/docs/guide/filter-queries.md)
- [x] [commands.md](../tree/main/site/docs/guide/commands.md)
- [x] [middleware.md](../tree/main/site/docs/guide/middleware.md)
- [x] [errors.md](../tree/main/site/docs/guide/errors.md)
- [x] [files.md](../tree/main/site/docs/guide/files.md)
- [x] [games.md](../tree/main/site/docs/guide/games.md)
- [x] [deployment-types.md](../tree/main/site/docs/guide/deployment-types.md)

#### Advanced

- [x] [README.md](../tree/main/site/docs/advanced/README.md)
- [x] [middleware.md](../tree/main/site/docs/advanced/middleware.md)
- [x] [structuring.md](../tree/main/site/docs/advanced/structuring.md)
- [ ] [scaling.md](../tree/main/site/docs/advanced/scaling.md)
- [ ] [reliability.md](../tree/main/site/docs/advanced/reliability.md)
- [ ] [flood.md](../tree/main/site/docs/advanced/flood.md)
- [ ] [transformers.md](../tree/main/site/docs/advanced/transformers.md)
- [ ] [proxy.md](../tree/main/site/docs/advanced/proxy.md)
- [x] [deployment.md](../tree/main/site/docs/advanced/deployment.md)

#### Introduction

- [x] [README.md](../tree/main/site/docs/plugins/README.md)
- [ ] [guide.md](../tree/main/site/docs/plugins/guide.md)

#### Built-in

- [ ] [session.md](../tree/main/site/docs/plugins/session.md)
- [ ] [keyboard.md](../tree/main/site/docs/plugins/keyboard.md)
- [ ] [inline-query.md](../tree/main/site/docs/plugins/inline-query.md)
- [ ] [media group.md](../tree/main/site/docs/plugins/media-group.md)

#### Official

- [ ] [conversations.md](../tree/main/site/docs/plugins/conversations.md)
- [ ] [menu.md](../tree/main/site/docs/plugins/menu.md)
- [ ] [stateless-question.md](../tree/main/site/docs/plugins/stateless-question.md)
- [ ] [runner.md](../tree/main/site/docs/plugins/runner.md)
- [ ] [hydrate.md](../tree/main/site/docs/plugins/hydrate.md)
- [ ] [auto-retry.md](../tree/main/site/docs/plugins/auto-retry.md)
- [ ] [transformer-throttler.md](../tree/main/site/docs/plugins/transformer-throttler.md)
- [ ] [ratelimiter.md](../tree/main/site/docs/plugins/ratelimiter.md)
- [ ] [files.md](../tree/main/site/docs/plugins/files.md)
- [ ] [i18n.md](../tree/main/site/docs/plugins/i18n.md)
- [ ] [fluent.md](../tree/main/site/docs/plugins/fluent.md)
- [ ] [router.md](../tree/main/site/docs/plugins/router.md)
- [ ] [emoji.md](../tree/main/site/docs/plugins/emoji.md)
- [ ] [parse-mode.md](../tree/main/site/docs/plugins/parse-mode.md)
- [ ] [chat-members.md](../tree/main/site/docs/plugins/chat-members.md)
- [ ] [commands.md](../tree/main/site/docs/plugins/commands.md)

#### Third-party

- [ ] [console-time.md](../tree/main/site/docs/plugins/console-time.md)
- [ ] [middlewares.md](../tree/main/site/docs/plugins/middlewares.md)
- [ ] [autoquote.md](../tree/main/site/docs/plugins/autoquote.md)

#### grammY

- [ ] [about.md](../tree/main/site/docs/resources/about.md)
- [ ] [faq.md](../tree/main/site/docs/resources/faq.md)
- [ ] [comparison.md](../tree/main/site/docs/resources/comparison.md)

#### Overview

- [ ] [comparison.md](../tree/main/site/docs/hosting/comparison.md)

#### Tutorials

- [ ] [deno-deploy.md](../tree/main/site/docs/hosting/deno-deploy.md)
- [ ] [supabase.md](../tree/main/site/docs/hosting/supabase.md)
- [ ] [cloudflare-workers.md](../tree/main/site/docs/hosting/cloudflare-workers.md)
- [ ] [cloudflare-workers-nodejs.md](../tree/main/site/docs/hosting/cloudflare-workers-nodejs.md)
- [ ] [heroku.md](../tree/main/site/docs/hosting/heroku.md)
- [ ] [fly.md](../tree/main/site/docs/hosting/fly.md)
- [ ] [firebase.md](../tree/main/site/docs/hosting/firebase.md)
- [ ] [gcf.md](../tree/main/site/docs/hosting/gcf.md)
- [ ] [vercel.md](../tree/main/site/docs/hosting/vercel.md)
- [ ] [vps.md](../tree/main/site/docs/hosting/vps.md)

**Comment by roziscoding** [comment]
Me and @kr4t0z have come to the following agreements, which might be important if anyone else decides to help us:

- Some terms will not be translated, as it's costumary to adopt some English words in portuguese. We can't really describe what's the rule for this, but it "feels weird" to translate some terms. These are the ones we've decided on so far:
  - Filter Query
  - Middleware
  - Long Polling
  - Webhook
- When refering to grammY directly, we'll add the missing article. So "grammY is x y z" becomes "O grammY é x y z"
- Telegram Bots is translated to "Bots para Telegram"
- "Bot API" is not translated, but "Telegram Bot API" is translated to "API de Bots do Telegram". Again, this is a matter of how it feels to translate or not translate it.
- "Getting Started" is translated to "Primeiros Passos"


That's it for now. We'll keep this comment updated with future agreements we may get to.

**Comment by KnorpelSenf** [comment]
It seems like these translations have stalled shortly after being started. We should probably keep this open for some more time and see if it can be picked up again. Otherwise, this and all referenced pull requests can be closed.

**Comment by roj1512** [comment]
All branches and open PQs related to Portuguese translations will be deleted and closed by Thursday if there is no further activity.

**Comment by KnorpelSenf** [comment]
^ the most reliable way to trigger a few more translations
